# Generated by Django 4.2.6 on 2024-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=50)),
                (
                    "sex",
                    models.IntegerField(
                        default=1, verbose_name=[(1, "Male"), (2, "Female")]
                    ),
                ),
                ("height", models.PositiveIntegerField(default=180)),
                ("weight", models.PositiveIntegerField(default=65)),
                ("age", models.PositiveIntegerField(default=16)),
                (
                    "state",
                    models.IntegerField(
                        default=2,
                        verbose_name=[
                            (1, "Cutting"),
                            (2, "Maintaining"),
                            (3, "Bulking"),
                        ],
                    ),
                ),
                (
                    "activity",
                    models.IntegerField(
                        default=3,
                        verbose_name=[
                            (1, "No"),
                            (2, "Light"),
                            (3, "Moderate"),
                            (4, "Very Active"),
                            (5, "Extra Activte"),
                        ],
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
